# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      GIT_COMMIT=$(git rev-parse --short HEAD)
      
      echo "GIT_COMMIT: ${GIT_COMMIT}"
      
      #
      # set env variable to allow next task to consume 
      #
      echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      dt=$(date '+%d/%m/%Y %H:%M:%S');
      echo "$dt"

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'

#- task: Npm@1
#  inputs:
#    command: 'custom'
#    customCommand: 'run test:u'
#  displayName: 'Testing npm'  

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit.xml'
  condition: always()
  displayName: 'Upload junit test results'
  
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'config set access public --global'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: Docker@2
  inputs:
    containerRegistry: 'polarity-acr'
    repository: 'data-service'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    addPipelineData: false
    tags: |
      $(Build.SourceBranchName)
      $(GIT_COMMIT)
